services:
  camel:
    image: 904534089871.dkr.ecr.us-west-2.amazonaws.com/camel-app:latest
    restart: unless-stopped
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env.docker
    environment:
      - DB_HOST=pgvector
      - DB_USER=postgres
      - MEDIA_ROOT=/app/media
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - pgvector

  huey:
    image: 904534089871.dkr.ecr.us-west-2.amazonaws.com/camel-app:latest
    restart: unless-stopped
    command: python manage.py run_huey
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env.docker
    environment:
      - DB_HOST=pgvector
      - DB_USER=postgres
      - MEDIA_ROOT=/app/media
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - pgvector
      - camel

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - camel

  redis:
    image: redis:latest
    restart: unless-stopped

  pgvector:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  media_volume:
  static_volume:
  pgvector_data: